name: Push To Production WorkFlow

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy package to cloud server
        uses: appleboy/ssh-action@master
        env:
            PAT: ${{ secrets.PAT }}
            DEPLOY_PATH: ${{ secrets.DEPLOY_PATH}}
            DOT_HTACCESS: ${{ secrets.DOT_HTACCESS }}
            ROBOTS_DOT_TEXT: ${{ secrets.ROBOTS_DOT_TEXT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PAT, DEPLOY_PATH, DOT_HTACCESS, ROBOTS_DOT_TEXT
          script: |
            sudo mkdir -p /tmp/repo
            sudo chmod -R 777 /tmp/repo
            cd /tmp
            sudo git clone https://$PAT@github.com/username/repo.git
            cd /tmp/repo
            sudo git checkout main
            sudo npm install && npm run build
            sudo rm -r $DEPLOY_PATH/public_html-old
            sudo mv $DEPLOY_PATH/public_html $DEPLOY_PATH/public_html-old
            sudo mkdir -p $DEPLOY_PATH/public_html
            sudo mv /tmp/repo/dist/* $DEPLOY_PATH/public_html
            sudo rm -r /tmp/repo
            cd $DEPLOY_PATH/public_html
            sudo touch .htaccess
            echo "$DOT_HTACCESS" | sudo tee .htaccess
            sudo touch robots.txt
            echo "$ROBOTS_DOT_TEXT" | sudo tee robots.txt
            sudo chmod -R 0755 $DEPLOY_PATH/public_html
